# Generated by Django 6.0.2 on 2026-03-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
