# Generated by Django 6.0.2 on 2026-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Novo'), ('preparing', 'Em preparo'), ('ready', 'Pronto'), ('delivered', 'Entregue')], default='new', max_length=20),
        ),
    ]
